apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-webapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: acme-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acme-webapp
    spec:
      containers:
      - name: acme-webapp
        image: us-central1-docker.pkg.dev/niropsapp-prod/acme-cr/acme-webapp:1.0
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 8080
